# Architecture identifier.
arch = "aarch64" # str
# Platform package.
package = "axplat-aarch64-d3000m-n80-laptop" # str
# Platform identifier.
platform = "axplat-aarch64-d3000m-n80-laptop" # str
# Stack size of each task.
task-stack-size = 0x40000 # uint
# Number of timer ticks per second (Hz). A timer tick may contain several timer
# interrupts.
ticks-per-sec = 100 # uint

#
# Device specifications
#
[devices]
# GIC Distributor base address
gicd-paddr = 0xfe600000 # uint
# GICR Address of rk3588
gicr-paddr = 0xfe680000 # uint
# IPI interrupt num
ipi-irq = 1 # uint
# MMIO ranges with format (`base_paddr`, `size`).
mmio-ranges = [
    [0x1800_2000, 0x1000]
] # [(uint, uint)]
# End PCI bus number (`bus-range` property in device tree).
pci-bus-end = 0xff # uint
# Base physical address of the PCIe ECAM space.
pci-ecam-base = 0x40_1000_0000 # uint
# PCI device memory ranges (`ranges` property in device tree).
pci-ranges = [] # [(uint, uint)]
# pl031@9010000 {
#     clock-names = "apb_pclk";
#     clocks = <0x8000>;
#     interrupts = <0x00 0x02 0x04>;
#     reg = <0x00 0x9010000 0x00 0x1000>;
#     compatible = "arm,pl031\0arm,primecell";
# };
# RTC (PL031) Address
rtc-paddr = 0x901_0000 # uint
# Timer interrupt num (PPI, physical timer).
timer-irq = 30 # uint
# UART IRQ number (SPI, 1)
uart-irq = 33 # uint
# UART Address
uart-paddr = 0x1800_2000 # uint
virtio-mmio-ranges = [] # [(uint, uint)]

#
# Platform configs
#
[plat]
# Stack size on bootstrapping. (256K)
boot-stack-size = 0x40000 # uint
# Kernel address space base.
kernel-aspace-base = "0xffff_0000_0000_0000" # uint
# Kernel address space size.
kernel-aspace-size = "0x0000_ffff_ffff_f000" # uint
# Base physical address of the kernel image.
kernel-base-paddr = 0x8000_0000 # uint
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_0000_8000_0000" # uint
# Maximum number of CPUs. For platforms that do not support runtime CPU number
# detection, it's also the number of CPUs to boot.
max-cpu-num = 1 # uint
# Offset of bus address and phys address. some boards, the bus address is
# different from the physical address.
phys-bus-offset = 0 # uint
# Base address of the whole physical memory.
phys-memory-base = 0x8000_0000 # uint
# Size of the whole physical memory. (128M)
phys-memory-size = 0x800_0000 # uint
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_0000_0000_0000" # uint
# PSCI
psci-method = "hvc" # str
